"""empty message

Revision ID: 59d961afbed6
Revises: 4f12fad5abb1
Create Date: 2017-11-01 17:27:48.694440

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import Column, INTEGER, ForeignKey


# revision identifiers, used by Alembic.
revision = '59d961afbed6'
down_revision = '4f12fad5abb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Return_Request',
    Column('age', INTEGER)
)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Return_Request', 'age')