"""empty message

Revision ID: f8a7ddd78440
Revises: 59d961afbed6
Create Date: 2017-11-01 17:47:21.504158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a7ddd78440'
down_revision = '59d961afbed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('status_change', sa.String(length=60), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    # ### end Alembic commands ###
